name: ci

on:
  push:
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
  checks: write

jobs:
  Build:
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run tests
        run: dotnet test

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Tests Result
          path: test/TestResults/*/iPanel-Host.Tests.trx
          reporter: dotnet-trx
